language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-21.0.2
    - android-21
    - extra-android-support
    - tools
    - platform-tools
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
  - sudo rm -r /usr/local/gradle
  - curl -LO https://services.gradle.org/distributions/gradle-2.1-bin.zip
  - unzip -q gradle-2.1-bin.zip
  - sudo mv gradle-2.1 /usr/local/gradle

script:
    - gradle -v
    - gradle build
    - gradle test
