language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - build-tools-21.1.2
    - android-21
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-21

before_install:
  - sudo rm -r /usr/local/gradle
  - curl -LO https://services.gradle.org/distributions/gradle-2.2-bin.zip
  - unzip -q gradle-2.2-bin.zip
  - sudo mv gradle-2.2 /usr/local/gradle

script:
    - gradle -v
    - gradle build
    - gradle test
